# Generated by Django 4.2.5 on 2023-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sencuisineByfa", "0003_alter_recipeingredient_quantite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name_plural": "User Profiles"},
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
